### ISSUE TITLE
Defaults pattern support

### ISSUE THREAD

**Issue by azu** [azu/intelli-espower-loader#8]
Currently, if `directories.test` is not found in package.json,  `intelli-espower-loader` have thrown error.
We will fix this,  `intelli-espower-loader` use `'test/**/*.js'` as defaults pattern.

Change to suit these similar library:

- https://github.com/twada/espower-coffee
- https://github.com/azu/espower-6to5
- https://github.com/yosuke-furukawa/espower-traceur

**Comment by azu** [comment]
Test this branch.

> npm install -D mocha https://api.github.com/repos/azu/intelli-espower-loader/tarball/defaults-pattern power-assert

**Comment by azu** [comment]
This idea come form @yosuke-furukawa and @twada
Thanks for the suggestion :sparkles:

**Comment by twada** [comment]
@azu Great!

**Comment by azu** [comment]
Realsed [0.6.0](https://github.com/azu/intelli-espower-loader/releases/tag/0.6.0 "0.6.0").
